import { motion } from 'framer-motion'
import { ArrowUpRight, Code2, MapPin, Sparkles } from 'lucide-react'
import PageIntro from '../components/PageIntro'
import { usePortfolioContent } from '../content/ContentContext'

export default function About() {
  const { profile } = usePortfolioContent()
  return <main className="page-wrap"><PageIntro eyebrow="Persona" title="Curious by nature. Precise by practice." copy={profile.intro} /><div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><motion.article initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="content-card p-8 md:p-12"><p className="eyebrow">/ Profile</p><p className="text-xl leading-9 md:text-3xl md:leading-[1.5]">{profile.about}</p><p className="mt-7 text-muted">{profile.quote}</p></motion.article><div className="grid gap-4"><article className="content-card p-7"><MapPin className="mb-6 text-accent"/><p className="eyebrow">Location</p><h2 className="text-3xl font-semibold">{profile.location}</h2><p className="mt-2 font-mono text-xs text-muted">{profile.timezone}</p></article><article className="content-card p-7"><Sparkles className="mb-6 text-green"/><p className="eyebrow">Current focus</p><h2 className="text-2xl font-semibold">AI systems & polished digital products</h2></article></div></div><div className="mt-4 grid gap-4 md:grid-cols-3">{[['01','GROWTH','Explore systems until the hidden structure becomes clear.'],['02','FOCUS','Give important problems the time and precision they deserve.'],['03','CRAFT','Make every interaction and line of code intentional.']].map(([n,title,copy])=><article key={n} className="content-card p-7"><span className="font-mono text-xs text-accent">{n}</span><Code2 className="my-8 text-muted"/><h3 className="font-mono text-sm tracking-widest">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{copy}</p></article>)}</div><div className="mt-4 content-card flex flex-col gap-6 p-8 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow">Collaboration</p><h2 className="text-3xl font-semibold tracking-tight">Have a problem worth solving?</h2></div><a href={`mailto:${profile.email}`} className="button button-primary">Let’s talk <ArrowUpRight size={16}/></a></div></main>
}
